name: Update Screenshot
on: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
      # Used to pull python distributions from actions/python-versions. Since there's a default, this is typically not supplied by the user.
        token: ${{ github.TOKEN }} # optional, default is ${{ github.token }}
    - name: Download
      run: |
        python main.py
        

    - name: Push
      run: |
        git config --global user.email "2071916845@qq.com"
        git config --global user.name "it985"
        git add -A
        git commit --allow-empty -m "Update Bing Wallpaper"
        #git pull origin master
        git push origin master
    - name: Delete Workflow Runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 7
        keep_minimum_runs: 6
